[package]
name = "precip"
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]

[dependencies]
failure = "0.1.1"
log = "0.4.1"
env_logger = "0.5.10"
serde = "1.0.55"
serde_json = "1.0.17"
serde_derive = "1.0.55"
diesel = { version = "1.2.2", features = ["chrono", "postgres", "uuid"] }
dotenv = "0.11.0"
uuid = "0.6.3"
rand = "0.4.2"
chrono = { version = "0.4.2", features = ["serde"] }
rusoto_s3 = "0.32.0"
rusoto_core = "0.32.0"
tokio = "0.1.6"
