[db]
hosts = ["http://localhost:8086"]

[db.credentials]
username = "precip"
password = "hunter2"
database = "precip"

[plant.a9ccd14f-eedf-48a7-bd6c-9fefab0ddeea]
name = "Basil"
description = """
*basilikum*

Half shade, lots of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-0", distance = "100cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 18 }

[plant.bb789398-6001-4a00-97fc-5dfeab297509]
name = "French Tarragon"
description = """
*artemisia dracunculus*

Sunny/half shade, not too much water, normal fertilization, **edible**.
"""
moisture = { channel = "48-1", distance = "100cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 23 }

[plant.641e4ff8-5a2b-4450-8ada-7a52ca1f9b0f]
name = "Chives"
description = """
*allium schoenoprasum*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-2", distance = "150cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 24 }

[plant.36dd6ec7-2538-426c-8d1a-8f6542458f5a]
name = "Moroccan Mint"
description = """
*mentha x villosa*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-3", distance = "150cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 25 }

########################################################################################################################
########################################################################################################################
########################################################################################################################

[plant.3767a85a-0016-411e-883c-6c50b25efe54]
name = "Rosemary"
description = """
*rosmarinus officinalis*

Sunny, not too much water, normal fertilization, **edible**.
"""
moisture = { channel = "49-0", distance = "200cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 12 }

[plant.3c11b762-277c-4458-85bc-00418b333fb3]
name = "Lemon balm"
description = """
*melissa officinalis*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "49-1", distance = "200cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 16 }

[plant.e62703ea-b955-47e1-80ea-d516a49bbdd1]
name = "Coriander"
description = """
*coriandrum satvium*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "49-2", distance = "250cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.1, max = 0.4 }
pump = { channel = 20 }

[plant.25406e3f-fa8d-4d1e-9d13-c2a5c66de359]
name = "Chili 'Tapas'"
description = """
*capiscum annuum*

Sunny, should have long water/dry cycles, normal fertilization, **edible**.
"""
moisture = { channel = "49-3", distance = "300cm", voltage_wet = 1.680187463760376, voltage_dry = 2.6495625972747803, min = 0.01, max = 0.02 }
pump = { channel = 21 }
