[db]
hosts = ["http://localhost:8086"]

[db.credentials]
username = "precip"
password = "hunter2"
database = "precip"

[plant.a9ccd14f-eedf-48a7-bd6c-9fefab0ddeea]
name = "Basil"
description = """
*basilikum*

Half shade, lots of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-0", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 18, enabled = true, schedule = { start = "0 0,15,30,45 6-21 * * *", duration_seconds = 1 } }

[plant.bb789398-6001-4a00-97fc-5dfeab297509]
name = "French Tarragon"
description = """
*artemisia dracunculus*

Sunny/half shade, not too much water, normal fertilization, **edible**.
"""
moisture = { channel = "48-1", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 23, enabled = true, schedule = { start = "0 1,16,31,46 6-21 * * *", duration_seconds = 1 } }

[plant.641e4ff8-5a2b-4450-8ada-7a52ca1f9b0f]
name = "Chives"
description = """
*allium schoenoprasum*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-2", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 24, enabled = true, schedule = { start = "0 2,17,32,47 6-21 * * *", duration_seconds = 1 } }

[plant.36dd6ec7-2538-426c-8d1a-8f6542458f5a]
name = "Moroccan Mint"
description = """
*mentha x villosa*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "48-3", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 25, enabled = true, schedule = { start = "0 3,18,33,48 6-21 * * *", duration_seconds = 1 } }

########################################################################################################################
########################################################################################################################
########################################################################################################################

[plant.3767a85a-0016-411e-883c-6c50b25efe54]
name = "Rosemary"
description = """
*rosmarinus officinalis*

Sunny, not too much water, normal fertilization, **edible**.
"""
moisture = { channel = "49-0", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 12, enabled = true, schedule = { start = "0 4,19,34,49 6-21 * * *", duration_seconds = 1 } }

[plant.3c11b762-277c-4458-85bc-00418b333fb3]
name = "Lemon balm"
description = """
*melissa officinalis*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "49-1", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 16, enabled = true, schedule = { start = "0 5,20,35,50 6-21 * * *", duration_seconds = 1 } }

[plant.e62703ea-b955-47e1-80ea-d516a49bbdd1]
name = "Coriander"
description = """
*coriandrum satvium*

Sunny/half shade, normal amount of water, normal fertilization, **edible**.
"""
moisture = { channel = "49-2", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 20, enabled = true, schedule = { start = "0 6,21,36,51 6-21 * * *", duration_seconds = 1 } }

[plant.25406e3f-fa8d-4d1e-9d13-c2a5c66de359]
name = "Chili 'Tapas'"
description = """
*capiscum annuum*

Sunny, should have long water/dry cycles, normal fertilization, **edible**.
"""
moisture = { channel = "49-3", voltage_wet = 1.5, voltage_dry = 2.1, min = 0.2, max = 0.6 }
pump = { channel = 21, enabled = true, schedule = { start = "0 7,22,37,52 6-21 * * *", duration_seconds = 1 } }
