[plant.a9ccd14f-eedf-48a7-bd6c-9fefab0ddeea]
name = "Basil"
description = "Basilikum: Half shade, lots of water, normal fertilization, edible"
max_moisture = 1.4
min_moisture = 1.3
moisture_channel = 0
pump_channel = 18

[plant.bb789398-6001-4a00-97fc-5dfeab297509]
name = "French Tarragon"
description = "Artemisia Dracunculus: Sunny/half shade, not too much water, normal fertilization, edible"
max_moisture = 1.2
min_moisture = 1.15
moisture_channel = 1
pump_channel = 23

[plant.641e4ff8-5a2b-4450-8ada-7a52ca1f9b0f]
name = "Chives"
description = "Allium Schoenoprasum: Sunny/half shade, normal amount of water, normal fertilization, edible"
max_moisture = 1.3
min_moisture = 1.25
moisture_channel = 2
pump_channel = 24

[plant.36dd6ec7-2538-426c-8d1a-8f6542458f5a]
name = "Moroccan Mint"
description = "Mentha X Villosa: Sunny/half shade, normal amount of water, normal fertilization, edible"
max_moisture = 1.3
min_moisture = 1.25
moisture_channel = 3
pump_channel = 25
